version: '3.8'
services:
    admin:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            DB_HOST: admin_db
            DB_DATABASE: admin_database
            DB_USERNAME: admin_user
            DB_PASSWORD: admin_pass
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app:rw
        ports:
            - "8000:8000"
        depends_on:
            - admin_db

    queue:
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan queue:work'
        environment:
            DB_HOST: admin_db
            DB_DATABASE: admin_database
            DB_USERNAME: admin_user
            DB_PASSWORD: admin_pass
        depends_on:
            - admin_db

    admin_db:
        image: mysql:5.7.22
        environment:
            MYSQL_DATABASE: admin_database
            MYSQL_USER: admin_user
            MYSQL_PASSWORD: admin_pass
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
