services:
    app:
        container_name: influencer_app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8003:8000"
        depends_on:
            - influencer_db
            - redis
            - mailhog
        volumes:
            - .:/var/www
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        working_dir: /var/www
        command: php artisan serve --host=0.0.0.0 --port=8000

    influencer_db:
        container_name: influencer_db
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: influencer_database
            MYSQL_USER: influencer_user
            MYSQL_PASSWORD: password
        ports:
            - "33070:3306"
        volumes:
            - db_data:/var/lib/mysql

    redis:
        container_name: influencer_redis
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data


    mailhog:
        container_name: influencer_mailhog
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"

volumes:
    db_data:
    redis_data:
