name: laravel-app

services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8003:8000"
        depends_on:
            - influencer_db
            - redis
            - mailcatcher
        volumes:
            - .:/var/www
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - CACHE_DRIVER=redis
            - SESSION_DRIVER=redis
            - REDIS_HOST=redis
            - MAIL_MAILER=smtp
            - MAIL_HOST=mailcatcher
            - MAIL_PORT=1025
            - MAIL_USERNAME=null
            - MAIL_PASSWORD=null
            - MAIL_ENCRYPTION=null
        working_dir: /var/www
        command: php artisan serve --host=0.0.0.0

    influencer_db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: influencer_database
            MYSQL_USER: influencer_user
            MYSQL_PASSWORD: password
        ports:
            - "33070:3306"
        volumes:
            - db_data:/var/lib/mysql

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data


    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - "1080:1080"   # Web interface
            - "1025:1025"   # SMTP port

volumes:
    db_data:
    redis_data:
