services:
    app:
        container_name: users_app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8004:8000"
        depends_on:
            - users_db
        volumes:
            - .:/var/www
        environment:
            DB_CONNECTION: mysql
            DB_HOST: users_db
            DB_PORT: 3306
            DB_DATABASE: users_database
            DB_USERNAME: users_username
            DB_PASSWORD: password
        working_dir: /var/www
        command: 'php artisan serve --host=0.0.0.0 --port=8004'
        networks:
            - app_network

    users_db:
        container_name: users_db
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: users_database
            MYSQL_USER: users_username
            MYSQL_PASSWORD: password
        ports:
            - "33072:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app_network

volumes:
    db_data:

networks:
    app_network:
        external: true
