services:
    app:
        container_name: users_app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8004:8000"
        depends_on:
            - db
        volumes:
            - .:/var/www
        environment:
            DB_HOST: users_db
            DB_DATABASE: users
            DB_USERNAME: root
            DB_PASSWORD: root
        working_dir: /var/www
        command: 'php artisan serve --host=0.0.0.0 --port=8004'

    db:
        container_name: users_db
        image: mysql:8.0
        environment:
            DB_HOST: root
            DB_DATABASE: users_database
            DB_USERNAME: users_user
            DB_PASSWORD: password
        ports:
            - "33072:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
