services:
    queue:
        container_name: email_queue
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - mailhog
        volumes:
            - .:/app
        working_dir: /app
        command: php artisan queue:work --verbose --tries=3 --timeout=90

    mailhog:
        container_name: email_mailhog
        image: mailhog/mailhog
        ports:
        - "1025:1025"  # SMTP port
        - "8025:8025"  # Web UI port
