name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-admin-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.2', '8.3']

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
        coverage: none

    - uses: actions/checkout@v4
    - name: Copy .env
      run: |
        cd laravel-admin
        php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Update Dependencies
      run: |
        cd laravel-admin
        composer update --no-ansi --no-interaction --prefer-dist

    - name: Install Dependencies
      run: |
        cd laravel-admin
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: |
        cd laravel-admin
        php artisan key:generate

    - name: Directory Permissions
      run: |
        cd laravel-admin
        chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        cd laravel-admin
        mkdir -p database
        touch database/database.sqlite

    - name: Migrate with seeds via sqlite
      run: |
        cd laravel-admin
        php artisan migrate --seed

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: |
        cd laravel-admin
        php artisan test